#!/usr/bin/env python
"""
Example code to demo mllib using CIFAR10

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import numpy as np
import sys
import keras

import mllib
from mllib import train
from mllib import test

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example to show how to use mllib.
    """

    log.info("Starting cifar10 example")

    log.info("Loading data")
    (x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data() # https://keras.io/datasets/

    log.info("Training data")
    cost = train("cifar10", x_train, y_train, num_classes=10, num_epochs=100, net_type=mllib.RESNET_SMALL)
    log.info("Training completed with cost: %f" % cost)

    log.info("Testing accuracy")
    accuracy = test("cifar10", x_test, y_test, num_classes=10, net_type=mllib.RESNET_SMALL)
    log.info("Test completed with accuracy: %f" % accuracy)

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
