#!/usr/bin/env python
"""
Example code to demo mllib using LFW.

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

from pathlib import Path
import numpy as np
import sys
import keras

import mllib
from mllib import train
from mllib import test
from mllib.dataload import load_image_data

LFW_DIR = Path("../../../../../ai/dataset/UMassFaceData/lfw")

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example to show how to use mllib.
    """

    log.info("Starting LFW example")

    log.info("Loading data")
    (x_train, y_train), (x_test, y_test), (class_id_to_label_dict, label_to_class_id_dict) = load_image_data("lfw_vgg19", LFW_DIR)

    num_classes = len(class_id_to_label_dict.keys())
    log.info("Training data")
    cost = train("lfw_vgg19", x_train, y_train, num_classes, num_epochs=50, x_test=x_test, y_test=y_test, net_type=mllib.VGG19)
    log.info("Training completed with cost: %f" % cost)

    log.info("Testing accuracy")
    accuracy = test("lfw_vgg19", x_test, y_test, num_classes, net_type=mllib.VGG19)
    log.info("Test completed with accuracy: %f" % accuracy)

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
