#!/usr/bin/env python
"""
Example code to demo mllib using MNIST

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import numpy as np
import sys
import keras

from mllib import train
from mllib import test

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example to show how to use mllib.
    """

    log.info("Starting MNIST exapmle")

    log.info("Loading data")
    (x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

    log.info("Training data")
    cost = train("mnist", x_train, y_train, num_classes=10)
    log.info("Training completed with cost: %f" % cost)

    log.info("Testing accuracy")
    accuracy = test("mnist", x_test, y_test, num_classes=10)
    log.info("Test completed with accuracy: %f" % accuracy)

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
